import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar/NavBar";
import { AuthProvider } from "@/providers/AuthProvider/AuthProvider";

export const metadata: Metadata = {
  title: "Minha loja virtual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider> {/* TODO:colocar o CounterProvider */}
          <NavBar />
          <div className="container mx-auto">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
